name: Government Open and Structured Content Models
markdown: redcarpet
pygments: true
baseurl: /Open-and-Structured-Content-Models
redcarpet:
 extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
